export class Abreviaturas {
    arrayAbreviaturas: any;
    constructor() {
        this.arrayAbreviaturas = [
            ['adj. invar.', 'adjetivo invariable'],
            ['adj.', 'adjetivo'],
            ['adj./s.', 'adjetivo/sustantivo'],
            ['adv.','adverbio'],
            ['afect.', 'afectivo'],
            ['amaz.', 'amazónico'],
            ['ant.', 'antioqueño caldense'],
            ['cauc.-vall.', 'caucano valluno'],
            ['cund.-boy.','cundiboyacense'],
            ['delic.', 'delincuencial'],
            ['dep.', 'deportes'],
            ['desp.', 'despectivo'],
            ['drog.', 'drogadicción'],
            ['est.', 'estudiantil'],
            ['euf.', 'eufemismo'],
            ['f.', 'femenino'],
            ['humor.', 'humorístico'],
            ['inf.', 'informal'],
            ['inform.', 'informática'],
            ['insult.', 'insulto'],
            ['interj.', 'interjección'],
            ['irón.', 'irónico'],
            ['juv.', 'juvenil'],
            ['llan.', 'llanero'],
            ['m.', 'masculino'],
            ['nar.', 'nariñense'],
            ['narc.', 'narcotráfico'],
            ['obsol.', 'obsolescente'],
            ['Pacíf.', 'Pacífico'],
            ['pl.', 'plural'],
            ['pref.', 'prefijo'],
            ['prep.', 'preposición'],
            ['prnl.', 'verbo pronominal'],
            ['pron.', 'pronombre'],
            ['rur.', 'rural'],
            ['s. amb.', 'sustantivo ambiguo'],
            ['s. com.', 'sustantivo común'],
            ['s.', 'sustantivo'],
            ['s./adj.', 'sustantivo/adjetivo'],
            ['sant.', 'santandereano'],
            ['suf.', 'sufijo'],
            ['tabú', 'tabú'],
            ['tb.', 'también'],
            ['tol-huil.', 'tolimense huilense'],
            ['u. m. c. prnl.', 'usado más como pronominal'],
            ['u. m. en pl.', 'usado más en plural'],
            ['u. t. c pl.', 'usado también como plural'],
            ['u. t. c. prnl.', 'usado también como pronominal'],
            ['urb.', 'urbano'],
            ['v.', 'verbo'],
            ['vulg.', 'vulgar']
    ]}
}
